[package]
name = "successive_romaji"
version = "0.1.1"
edition = "2021"

[lib]
name = "successive_romaji"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", optional = true }

[features]
default = []
